### ISSUE TITLE
Copy file passing breaks in dispatched workflows 

### ISSUE THREAD

**Issue by zulissimeta** [Quantum-Accelerators/quacc#1742] opened 2024-02-22 15:37 UTC
### Details about the quacc environment

- **quacc version**: latest
- **Python version**: 3.11

### What is the issue?

Any function that operates on inputs of a previous function should be a job so that the dependency is clear and the results are non-blocking. This is mostly what happens in quacc, including when looking up parameters like results["key"].

However, when passing file locations between tasks, file paths are specified as functions of the previous inputs using Path:
https://github.com/Quantum-Accelerators/quacc/blob/main/src/quacc/recipes/vasp/core.py#L173

This causes a problem when running in prefect (and possibly others), because here `Path(summary[...]) / 'WAVECAR'` is actually a function operating on the previous summary, and Path() cannot be resolved until sometime in the future when the summary is actually available, similar to how __getitem__ is monkey patched in prefect with quacc. 

One possible fix for this is to use a helper function job for these cases everywhere copy_files is specified in quacc:
```
@job
def file_locations(summary, file_names):
    return [Path(summary["dir_name"]) / file_name for file_name in file_names]
```

### How can we easily reproduce the issue?

When using prefect as the backend:
```python
from quacc.recipes.vasp.core import double_relax_job
double_relax(atoms)
```

**Comment by Andrew-S-Rosen** [comment] 2024-02-22 17:05
Thanks for the report, @zulissimeta! I'm still trying to wrap my head around this one.

## Clarification

In the `double_relax_job`, both relaxations are not a `Job`s but rather regular functions since their decorators are stripped. This means that `summary["dir_name"]` should not be a `Future` but rather would be run sequentially and have a value available in real-time. Am I misunderstanding something with this example?

https://github.com/Quantum-Accelerators/quacc/blob/5c883113fdb36f5beb7797561ea3727d040f04cf/src/quacc/recipes/vasp/core.py#L163-L175

If that was just a representative example but didn't end up highlighting the problem, perhaps looking at a different recipe might be illustrative:

https://github.com/Quantum-Accelerators/quacc/blob/5c883113fdb36f5beb7797561ea3727d040f04cf/src/quacc/recipes/vasp/mp.py#L351-L362

In the above example, `relax_results["relax2"]` is a `Future` and therefore so is the `Path`. Is this representative of the problem? 

If the issue is simply that `Path[list[Future]]` (and `Path[Future]`) is a problem since the `Job` can't know to autoresolve it, what about us not using `Path` at all. Would doing `f"{summary1['dir_name']) / "WAVECAR"` be okay, or is the `str`-based `Future` going to cause the same issues? It'd be nice to avoid another `@job` call just for the sake of Path resolving. It's fine if you're using a Dask cluster kind of setup, but if one were to have a conventional one-job-is-one-Slurm-allocation setup, it's a lot of needless queuing.

To the best of my knowledge, I don't think this is an issue in (at least some of the) other workflow engines.

**Comment by Andrew-S-Rosen** [comment] 2024-02-22 17:31
Update for the interested reader:

The issue is that we are doing `list[Path[Future]]` and the `Path()` function can't be called on a `Future`. The `Future` only gets resolved inside of a `@job` call, and we are doing `Path[Future]` before that.

There are many ways one might think about resolving this, but the best route in my opinion is to modify the `copy_files` keyword argument so it is something more like `copy_files=(relax_results["relax2"]["dir_name"], ["CHGCAR", "WAVECAR"])` that way the `Future.__getitem__` is what's passed without any other function calls being done on it.

I can take care of this, but potentially not until the weekend.

**Closed** 2024-02-29 17:02 UTC
Labels: bug, high-priority
