### ISSUE TITLE
Non-integer k-point generation

### ISSUE THREAD

**Issue by zulissimeta** [Quantum-Accelerators/quacc#1526] opened 2024-01-12 14:39 UTC
### Details about the quacc environment

- **quacc version**: latest
- **Python version**: 3.11

### What is the issue?

Two related but separate small bugs related to kpt generation routine (quacc.utils.kpt.convert_pmg_kpts):
1. The convert_pmg_kpts docstring claims that the output should be an ndarray, but the logic path using length_densities (and possibly others) yields a list
2. The length_densities logic path yields floating point kpts that cause problems in the ASE vasp calculator (which expects only integers).

Changing 
https://github.com/Quantum-Accelerators/quacc/blob/main/src/quacc/utils/kpts.py#L107
to `kpts = np.array(max_pmg_kpts.kpts[0]).astype(int)` 
fixes the problem for the example, but it could also make sense to add this after the if block to enforce an int array in either logic path. 

### How can we easily reproduce the issue?

```python
from quacc.utils.kpts import convert_pmg_kpts
from ase.build import bulk

convert_pmg_kpts({'length_densities': [50, 50, 1]}, bulk("Cu"))
```

**Comment by Andrew-S-Rosen** [comment] 2024-01-12 16:54
Thank you for the bug report! Good catch. Looks like I missed this one since, e.g. `[50, 50, 1] == [50.0, 50.0, 1.0]` and I didn't think to check for `int`. Fixed in #1527 with a regression test.

**Closed** 2024-01-12 17:23 UTC
Labels: bug
